// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC3525GettingStarted$Type } from "./ERC3525GettingStarted";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC3525GettingStarted"]: ERC3525GettingStarted$Type;
    ["contracts/ERC3525GettingStarted.sol:ERC3525GettingStarted"]: ERC3525GettingStarted$Type;
  }
}
